# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joshuahal/Documents/Modulus-Lite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joshuahal/Documents/Modulus-Lite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshuahal/Documents/Modulus-Lite/CMakeFiles /Users/joshuahal/Documents/Modulus-Lite//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshuahal/Documents/Modulus-Lite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ModulusLiteCAD

# Build rule for target.
ModulusLiteCAD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteCAD
.PHONY : ModulusLiteCAD

# fast build rule for target.
ModulusLiteCAD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/build
.PHONY : ModulusLiteCAD/fast

#=============================================================================
# Target rules for targets named ModulusLiteUI

# Build rule for target.
ModulusLiteUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteUI
.PHONY : ModulusLiteUI

# fast build rule for target.
ModulusLiteUI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/build
.PHONY : ModulusLiteUI/fast

#=============================================================================
# Target rules for targets named ModulusLitePlugin

# Build rule for target.
ModulusLitePlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLitePlugin
.PHONY : ModulusLitePlugin

# fast build rule for target.
ModulusLitePlugin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/build
.PHONY : ModulusLitePlugin/fast

#=============================================================================
# Target rules for targets named ModulusLiteTests

# Build rule for target.
ModulusLiteTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteTests
.PHONY : ModulusLiteTests

# fast build rule for target.
ModulusLiteTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/build
.PHONY : ModulusLiteTests/fast

#=============================================================================
# Target rules for targets named ModulusLiteCAD_autogen_timestamp_deps

# Build rule for target.
ModulusLiteCAD_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteCAD_autogen_timestamp_deps
.PHONY : ModulusLiteCAD_autogen_timestamp_deps

# fast build rule for target.
ModulusLiteCAD_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD_autogen_timestamp_deps.dir/build.make CMakeFiles/ModulusLiteCAD_autogen_timestamp_deps.dir/build
.PHONY : ModulusLiteCAD_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ModulusLiteCAD_autogen

# Build rule for target.
ModulusLiteCAD_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteCAD_autogen
.PHONY : ModulusLiteCAD_autogen

# fast build rule for target.
ModulusLiteCAD_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD_autogen.dir/build.make CMakeFiles/ModulusLiteCAD_autogen.dir/build
.PHONY : ModulusLiteCAD_autogen/fast

#=============================================================================
# Target rules for targets named ModulusLiteUI_autogen_timestamp_deps

# Build rule for target.
ModulusLiteUI_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteUI_autogen_timestamp_deps
.PHONY : ModulusLiteUI_autogen_timestamp_deps

# fast build rule for target.
ModulusLiteUI_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI_autogen_timestamp_deps.dir/build.make CMakeFiles/ModulusLiteUI_autogen_timestamp_deps.dir/build
.PHONY : ModulusLiteUI_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ModulusLiteUI_autogen

# Build rule for target.
ModulusLiteUI_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteUI_autogen
.PHONY : ModulusLiteUI_autogen

# fast build rule for target.
ModulusLiteUI_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI_autogen.dir/build.make CMakeFiles/ModulusLiteUI_autogen.dir/build
.PHONY : ModulusLiteUI_autogen/fast

#=============================================================================
# Target rules for targets named ModulusLitePlugin_autogen_timestamp_deps

# Build rule for target.
ModulusLitePlugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLitePlugin_autogen_timestamp_deps
.PHONY : ModulusLitePlugin_autogen_timestamp_deps

# fast build rule for target.
ModulusLitePlugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin_autogen_timestamp_deps.dir/build.make CMakeFiles/ModulusLitePlugin_autogen_timestamp_deps.dir/build
.PHONY : ModulusLitePlugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ModulusLitePlugin_autogen

# Build rule for target.
ModulusLitePlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLitePlugin_autogen
.PHONY : ModulusLitePlugin_autogen

# fast build rule for target.
ModulusLitePlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin_autogen.dir/build.make CMakeFiles/ModulusLitePlugin_autogen.dir/build
.PHONY : ModulusLitePlugin_autogen/fast

#=============================================================================
# Target rules for targets named ModulusLiteTests_autogen_timestamp_deps

# Build rule for target.
ModulusLiteTests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteTests_autogen_timestamp_deps
.PHONY : ModulusLiteTests_autogen_timestamp_deps

# fast build rule for target.
ModulusLiteTests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests_autogen_timestamp_deps.dir/build.make CMakeFiles/ModulusLiteTests_autogen_timestamp_deps.dir/build
.PHONY : ModulusLiteTests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ModulusLiteTests_autogen

# Build rule for target.
ModulusLiteTests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulusLiteTests_autogen
.PHONY : ModulusLiteTests_autogen

# fast build rule for target.
ModulusLiteTests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests_autogen.dir/build.make CMakeFiles/ModulusLiteTests_autogen.dir/build
.PHONY : ModulusLiteTests_autogen/fast

ModulusLiteCAD_autogen/mocs_compilation.o: ModulusLiteCAD_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.o

# target to build an object file
ModulusLiteCAD_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/ModulusLiteCAD_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.cpp.o

ModulusLiteCAD_autogen/mocs_compilation.i: ModulusLiteCAD_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.i

# target to preprocess a source file
ModulusLiteCAD_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/ModulusLiteCAD_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.cpp.i

ModulusLiteCAD_autogen/mocs_compilation.s: ModulusLiteCAD_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.s

# target to generate assembly for a file
ModulusLiteCAD_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/ModulusLiteCAD_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteCAD_autogen/mocs_compilation.cpp.s

ModulusLitePlugin_autogen/mocs_compilation.o: ModulusLitePlugin_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.o

# target to build an object file
ModulusLitePlugin_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/ModulusLitePlugin_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.cpp.o

ModulusLitePlugin_autogen/mocs_compilation.i: ModulusLitePlugin_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.i

# target to preprocess a source file
ModulusLitePlugin_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/ModulusLitePlugin_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.cpp.i

ModulusLitePlugin_autogen/mocs_compilation.s: ModulusLitePlugin_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.s

# target to generate assembly for a file
ModulusLitePlugin_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/ModulusLitePlugin_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLitePlugin_autogen/mocs_compilation.cpp.s

ModulusLiteTests_autogen/mocs_compilation.o: ModulusLiteTests_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteTests_autogen/mocs_compilation.o

# target to build an object file
ModulusLiteTests_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/ModulusLiteTests_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteTests_autogen/mocs_compilation.cpp.o

ModulusLiteTests_autogen/mocs_compilation.i: ModulusLiteTests_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteTests_autogen/mocs_compilation.i

# target to preprocess a source file
ModulusLiteTests_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/ModulusLiteTests_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteTests_autogen/mocs_compilation.cpp.i

ModulusLiteTests_autogen/mocs_compilation.s: ModulusLiteTests_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteTests_autogen/mocs_compilation.s

# target to generate assembly for a file
ModulusLiteTests_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/ModulusLiteTests_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteTests_autogen/mocs_compilation.cpp.s

ModulusLiteUI_autogen/mocs_compilation.o: ModulusLiteUI_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteUI_autogen/mocs_compilation.o

# target to build an object file
ModulusLiteUI_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ModulusLiteUI_autogen/mocs_compilation.cpp.o
.PHONY : ModulusLiteUI_autogen/mocs_compilation.cpp.o

ModulusLiteUI_autogen/mocs_compilation.i: ModulusLiteUI_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteUI_autogen/mocs_compilation.i

# target to preprocess a source file
ModulusLiteUI_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ModulusLiteUI_autogen/mocs_compilation.cpp.i
.PHONY : ModulusLiteUI_autogen/mocs_compilation.cpp.i

ModulusLiteUI_autogen/mocs_compilation.s: ModulusLiteUI_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteUI_autogen/mocs_compilation.s

# target to generate assembly for a file
ModulusLiteUI_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ModulusLiteUI_autogen/mocs_compilation.cpp.s
.PHONY : ModulusLiteUI_autogen/mocs_compilation.cpp.s

cad_adapter.o: cad_adapter.cpp.o
.PHONY : cad_adapter.o

# target to build an object file
cad_adapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/cad_adapter.cpp.o
.PHONY : cad_adapter.cpp.o

cad_adapter.i: cad_adapter.cpp.i
.PHONY : cad_adapter.i

# target to preprocess a source file
cad_adapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/cad_adapter.cpp.i
.PHONY : cad_adapter.cpp.i

cad_adapter.s: cad_adapter.cpp.s
.PHONY : cad_adapter.s

# target to generate assembly for a file
cad_adapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteCAD.dir/build.make CMakeFiles/ModulusLiteCAD.dir/cad_adapter.cpp.s
.PHONY : cad_adapter.cpp.s

plugin_main.o: plugin_main.cpp.o
.PHONY : plugin_main.o

# target to build an object file
plugin_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/plugin_main.cpp.o
.PHONY : plugin_main.cpp.o

plugin_main.i: plugin_main.cpp.i
.PHONY : plugin_main.i

# target to preprocess a source file
plugin_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/plugin_main.cpp.i
.PHONY : plugin_main.cpp.i

plugin_main.s: plugin_main.cpp.s
.PHONY : plugin_main.s

# target to generate assembly for a file
plugin_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLitePlugin.dir/build.make CMakeFiles/ModulusLitePlugin.dir/plugin_main.cpp.s
.PHONY : plugin_main.cpp.s

tests/test_core.o: tests/test_core.cpp.o
.PHONY : tests/test_core.o

# target to build an object file
tests/test_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_core.cpp.o
.PHONY : tests/test_core.cpp.o

tests/test_core.i: tests/test_core.cpp.i
.PHONY : tests/test_core.i

# target to preprocess a source file
tests/test_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_core.cpp.i
.PHONY : tests/test_core.cpp.i

tests/test_core.s: tests/test_core.cpp.s
.PHONY : tests/test_core.s

# target to generate assembly for a file
tests/test_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_core.cpp.s
.PHONY : tests/test_core.cpp.s

tests/test_routing.o: tests/test_routing.cpp.o
.PHONY : tests/test_routing.o

# target to build an object file
tests/test_routing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_routing.cpp.o
.PHONY : tests/test_routing.cpp.o

tests/test_routing.i: tests/test_routing.cpp.i
.PHONY : tests/test_routing.i

# target to preprocess a source file
tests/test_routing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_routing.cpp.i
.PHONY : tests/test_routing.cpp.i

tests/test_routing.s: tests/test_routing.cpp.s
.PHONY : tests/test_routing.s

# target to generate assembly for a file
tests/test_routing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteTests.dir/build.make CMakeFiles/ModulusLiteTests.dir/tests/test_routing.cpp.s
.PHONY : tests/test_routing.cpp.s

ui_panel.o: ui_panel.cpp.o
.PHONY : ui_panel.o

# target to build an object file
ui_panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ui_panel.cpp.o
.PHONY : ui_panel.cpp.o

ui_panel.i: ui_panel.cpp.i
.PHONY : ui_panel.i

# target to preprocess a source file
ui_panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ui_panel.cpp.i
.PHONY : ui_panel.cpp.i

ui_panel.s: ui_panel.cpp.s
.PHONY : ui_panel.s

# target to generate assembly for a file
ui_panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModulusLiteUI.dir/build.make CMakeFiles/ModulusLiteUI.dir/ui_panel.cpp.s
.PHONY : ui_panel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ModulusLiteCAD_autogen"
	@echo "... ModulusLiteCAD_autogen_timestamp_deps"
	@echo "... ModulusLitePlugin_autogen"
	@echo "... ModulusLitePlugin_autogen_timestamp_deps"
	@echo "... ModulusLiteTests_autogen"
	@echo "... ModulusLiteTests_autogen_timestamp_deps"
	@echo "... ModulusLiteUI_autogen"
	@echo "... ModulusLiteUI_autogen_timestamp_deps"
	@echo "... ModulusLiteCAD"
	@echo "... ModulusLitePlugin"
	@echo "... ModulusLiteTests"
	@echo "... ModulusLiteUI"
	@echo "... ModulusLiteCAD_autogen/mocs_compilation.o"
	@echo "... ModulusLiteCAD_autogen/mocs_compilation.i"
	@echo "... ModulusLiteCAD_autogen/mocs_compilation.s"
	@echo "... ModulusLitePlugin_autogen/mocs_compilation.o"
	@echo "... ModulusLitePlugin_autogen/mocs_compilation.i"
	@echo "... ModulusLitePlugin_autogen/mocs_compilation.s"
	@echo "... ModulusLiteTests_autogen/mocs_compilation.o"
	@echo "... ModulusLiteTests_autogen/mocs_compilation.i"
	@echo "... ModulusLiteTests_autogen/mocs_compilation.s"
	@echo "... ModulusLiteUI_autogen/mocs_compilation.o"
	@echo "... ModulusLiteUI_autogen/mocs_compilation.i"
	@echo "... ModulusLiteUI_autogen/mocs_compilation.s"
	@echo "... cad_adapter.o"
	@echo "... cad_adapter.i"
	@echo "... cad_adapter.s"
	@echo "... plugin_main.o"
	@echo "... plugin_main.i"
	@echo "... plugin_main.s"
	@echo "... tests/test_core.o"
	@echo "... tests/test_core.i"
	@echo "... tests/test_core.s"
	@echo "... tests/test_routing.o"
	@echo "... tests/test_routing.i"
	@echo "... tests/test_routing.s"
	@echo "... ui_panel.o"
	@echo "... ui_panel.i"
	@echo "... ui_panel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

